# -*- coding: utf-8 -*-
"""calculadora

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LZ71tDWrKmuWfD1HQOxo81h-pbsl2vC
"""

# calculadora
def calculadora(operacao,num1,num2):
 if operacao == "+":
  return num1 + num2
 elif operacao == "-":
  return num1 - num2
 elif operacao == "*":
  return num1 * num2
 elif operacao == "/":
  return num1 / num2
 else:
  return"Operação inválida"


print("Calculadora em  Python")
print("Insira os números e a operação desejada")
num1= float(input("Digite o primeiro número:"))
operacao= input("Digite a operação(+,-.*./):")
num2=float(input("Digite o segunbdo numero;"))

resultado = calculadora(operacao,num1,num2)
print(f'{num1} {operacao} {num2} = {round(resultado,2)}')