# -*- coding: utf-8 -*-
"""Estruturas de Dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTzQptVn7k7MPaLaf427vVYPXuQuR9nN

# **Exercícios**

## 1\. Listas

Criei uma lista chamada `filmes` com o nome dos 10 primeiros filmes mais bem avaliados no site no [IMDB](https://www.imdb.com/chart/top/). Imprima o resultado.
"""

filmes = ['Duna' , 'O esquadrão suicida' , ' eternos' , 'mortal combate' , 'Liga da Justica' , 'godzilla vs kong' , 'viuva negra' , 'army of the dead' , 'cruella' , 'shang-chi e a lenda dos dez aneis']
print(filmes)
print(type(filmes))

"""Simule a movimentação do *ranking*. Utilize os métodos `insert` e `pop` para trocar a posição do primeiro e do segundo filme da lista. Imprima o resultado.


"""

filmes = ['Duna'  ,'o esquadrão suicida' , ' eternos' , 'mortal combate' , 'Liga da Justica' , 'godzilla vs kong' , 'viuva negra' , 'army of the dead' , 'cruella' , 'shang-chi e a lenda dos dez aneis']
# inserir um elemento com substituir: list.insert(index, val)
filmes.insert(0,'o esquadrão sucida')
#remover um elemento pelo indice : list.pop(val)
print(filmes)
filmes_at = filmes.pop(2)
print(filmes_at)

# remover um elemento pelo valor : list.pop(val)
print(filmes)
filmes = filmes.pop(5)
print(filmes)

"""## 2\. Conjuntos

Aconteceu um erro no seu *ranking*. Simule a duplicação dos três últimos filmes da lista. Imprima o resultado.

Utiliza a conversão `set` e `list` para remover os valores duplicados. Imprima o resultado.
"""

filmes_01 =['dalmata', 'Duna', 'o esquadrão suicida', ' eternos']
filmes_02 = ['o esquadrão suicida', ' eternos', 'mortal combate', 'Liga da Justica']
filmes_03 = [ 'eternos', 'mortal combate', 'Liga da Justica', 'godzilla vs kong', 'viuva negra']
filmes_total = filmes_01 + filmes_02 + filmes_03
print(filmes_total)
print(type(filmes_total))

"""---"""

# remover um elemento no conjunto: set.remove(val)
filmes_total.remove('o esquadrão suicida')
print(filmes_total)

"""## 3\. Dicionários

Repita os exercícios da parte 1 (listas). Os elementos da lista `filmes` devem ser dicionários no seguinte formato: `{'nome': <nome-do-filme>, 'ano': <ano do filme>}, 'sinopse': <sinopse do filme>}`.
"""

filmes = ['Duna' , 'O esquadrão suicida' , ' eternos' , 'mortal combate' , 'Liga da Justica' , 'godzilla vs kong' , 'viuva negra' , 'army of the dead' , 'cruella' , 'shang-chi e a lenda dos dez aneis']
print(filmes)
print(type(filmes))

Duna = {
    'ano: 2021'
     'sinope: O lutador de MMA Cole Young não conhece sua herança, nem sabe o motivo do Imperador da Exoterra ter enviado seu melhor guerreiro, Sub-Zero, para ir atrás dele. Temendo pela segurança de sua família, ele se une a outros heróis para proteger a Terra.'
}
print(Duna)

O_esquadrão_suicida = {
    'ano: 2021 '
    'sinope: O governo envia os supervilões mais perigosos do mundo para a remota ilha de Corto Maltese, repleta de inimigos. Armados com armas de alta tecnologia, eles viajam pela selva perigosa em uma missão de busca e destruição com o Coronel Rick Flag.'
     }
print(O_esquadrão_suicida )